title: mrwconsulting/ciflex-samples
description: >-
  CICD Platform automates AWS CodePipeline setup with CDK, CodeBuild, DynamoDB,
  and Cognito, enhancing CI/CD workflows and integrating with ServiceCatalog.
tagline: >-
  CICD Platform automates AWS CodePipeline setup with CDK, CodeBuild, DynamoDB,
  and Cognito, enhancing CI/CD workflows and integrating with ServiceCatalog.
url: 'https://mrwconsulting.github.io'
canonical_url: 'https://mrwconsulting.github.io'
layout: page
markdown: kramdown
permalink: pretty
google_site_verification: OeGS0wbadQfPK17khgBr37EPrl70c4-V_gORkbjV5rg
defaults:
  - scope:
      path: ''
    values:
      layout: default
      seo_description_max_words: 160
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
